services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express_app_dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./prisma:/app/prisma
      - ./src:/app/src
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres_db_dev:5432/express_db?schema=public"
      CHOKIDAR_USEPOLLING: "true"   
    depends_on:
      - postgres_db_dev

  postgres_db_dev:
    image: postgres:latest
    container_name: postgres_db_dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: express_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
